# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: listener.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='listener.proto',
  package='Listener',
  syntax='proto3',
  serialized_pb=_b('\n\x0elistener.proto\x12\x08Listener\"\x1f\n\nSubRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\t\"\x1e\n\tSubResult\x12\x11\n\ttimestamp\x18\x01 \x01(\t2=\n\x07Service\x12\x32\n\x03sub\x12\x14.Listener.SubRequest\x1a\x13.Listener.SubResult0\x01\x62\x06proto3')
)




_SUBREQUEST = _descriptor.Descriptor(
  name='SubRequest',
  full_name='Listener.SubRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Listener.SubRequest.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=59,
)


_SUBRESULT = _descriptor.Descriptor(
  name='SubResult',
  full_name='Listener.SubResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Listener.SubResult.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['SubRequest'] = _SUBREQUEST
DESCRIPTOR.message_types_by_name['SubResult'] = _SUBRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubRequest = _reflection.GeneratedProtocolMessageType('SubRequest', (_message.Message,), dict(
  DESCRIPTOR = _SUBREQUEST,
  __module__ = 'listener_pb2'
  # @@protoc_insertion_point(class_scope:Listener.SubRequest)
  ))
_sym_db.RegisterMessage(SubRequest)

SubResult = _reflection.GeneratedProtocolMessageType('SubResult', (_message.Message,), dict(
  DESCRIPTOR = _SUBRESULT,
  __module__ = 'listener_pb2'
  # @@protoc_insertion_point(class_scope:Listener.SubResult)
  ))
_sym_db.RegisterMessage(SubResult)



_SERVICE = _descriptor.ServiceDescriptor(
  name='Service',
  full_name='Listener.Service',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=93,
  serialized_end=154,
  methods=[
  _descriptor.MethodDescriptor(
    name='sub',
    full_name='Listener.Service.sub',
    index=0,
    containing_service=None,
    input_type=_SUBREQUEST,
    output_type=_SUBRESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICE)

DESCRIPTOR.services_by_name['Service'] = _SERVICE

# @@protoc_insertion_point(module_scope)
