# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lm.helloworld.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lm.helloworld.proto',
  package='Lm',
  syntax='proto3',
  serialized_pb=_b('\n\x13lm.helloworld.proto\x12\x02Lm\"9\n\x11HelloworldRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03str\x18\x02 \x01(\t\x12\x0b\n\x03opt\x18\x03 \x01(\x05\".\n\x12HelloworldResponse\x12\x0b\n\x03str\x18\x01 \x01(\t\x12\x0b\n\x03opt\x18\x02 \x01(\x05\x32\x42\n\nlm_Service\x12\x34\n\x03sub\x12\x15.Lm.HelloworldRequest\x1a\x16.Lm.HelloworldResponseb\x06proto3')
)




_HELLOWORLDREQUEST = _descriptor.Descriptor(
  name='HelloworldRequest',
  full_name='Lm.HelloworldRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Lm.HelloworldRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='str', full_name='Lm.HelloworldRequest.str', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='opt', full_name='Lm.HelloworldRequest.opt', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=84,
)


_HELLOWORLDRESPONSE = _descriptor.Descriptor(
  name='HelloworldResponse',
  full_name='Lm.HelloworldResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='str', full_name='Lm.HelloworldResponse.str', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='opt', full_name='Lm.HelloworldResponse.opt', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=132,
)

DESCRIPTOR.message_types_by_name['HelloworldRequest'] = _HELLOWORLDREQUEST
DESCRIPTOR.message_types_by_name['HelloworldResponse'] = _HELLOWORLDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloworldRequest = _reflection.GeneratedProtocolMessageType('HelloworldRequest', (_message.Message,), dict(
  DESCRIPTOR = _HELLOWORLDREQUEST,
  __module__ = 'lm.helloworld_pb2'
  # @@protoc_insertion_point(class_scope:Lm.HelloworldRequest)
  ))
_sym_db.RegisterMessage(HelloworldRequest)

HelloworldResponse = _reflection.GeneratedProtocolMessageType('HelloworldResponse', (_message.Message,), dict(
  DESCRIPTOR = _HELLOWORLDRESPONSE,
  __module__ = 'lm.helloworld_pb2'
  # @@protoc_insertion_point(class_scope:Lm.HelloworldResponse)
  ))
_sym_db.RegisterMessage(HelloworldResponse)



_LM_SERVICE = _descriptor.ServiceDescriptor(
  name='lm_Service',
  full_name='Lm.lm_Service',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=134,
  serialized_end=200,
  methods=[
  _descriptor.MethodDescriptor(
    name='sub',
    full_name='Lm.lm_Service.sub',
    index=0,
    containing_service=None,
    input_type=_HELLOWORLDREQUEST,
    output_type=_HELLOWORLDRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LM_SERVICE)

DESCRIPTOR.services_by_name['lm_Service'] = _LM_SERVICE

# @@protoc_insertion_point(module_scope)
